### ISSUE TITLE
issue removing temporary files

### ISSUE THREAD

**Issue by ghost** [kushaldas/manualbox#11]
When editing a file with vim, temporary .swp files are generated. However, the files usually are removed when cleanly saving and exiting vim.
In my `~/secure` folder, .swp and .swx files are generated and not removed when closing the file. Manually removing the file yields

```{bash}
~/secured » rm .test.txt.swp
rm: cannot remove '.test.txt.swp': Invalid argument
```

I have to unlock the file first, e.g. with `cat .test.txt.swp` and then remove it with `rm`.

**Comment by kushaldas** [comment]
I can reproduce the issue.

**Comment by kushaldas** [comment]
The file is empty (no data), then the `unlink` is throwing the error.

```
DEBUG:fuse.log-mixin:-> unlink /hello.mp3 ()
DEBUG:fuse.log-mixin:<- unlink '[Unhandled Exception]'
ERROR:fuse:Uncaught exception from FUSE operation unlink, returning errno.EINVAL.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/fusepy.py", line 734, in _wrapper
    return func(*args, **kwargs) or 0
  File "/usr/lib/python3/dist-packages/fusepy.py", line 793, in unlink
    return self.operations('unlink', path.decode(self.encoding))
  File "/usr/lib/python3/dist-packages/fusepy.py", line 1251, in __call__
    ret = getattr(self, op)(path, *args)
  File "/home/kdas/code/manualbox/manualbox/__init__.py", line 261, in unlink
    self.data.pop(path)
KeyError: '/hello.mp3'

```
